name: Node.js CI

on:
  push:
    branches: [ "main" ]
    tags:
      - '*'
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run build
    
    - name: Archive Release
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        directory: build
        filename: 'latest.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
        
    - name: Upload Release
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      uses: ncipollo/release-action@v1
      with:
        artifacts: "latest.zip"
        token: ${{ secrets.GITHUB_TOKEN }}

